name: fate-srd-backend
recipe: drupal10
config:
  webroot: web
  database: mysql:8.0
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://fate-srd-backend.lndo.site"
